/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    'activation': RouteRecordInfo<'activation', '/activation', Record<never, never>, Record<never, never>>,
    'camera': RouteRecordInfo<'camera', '/camera', Record<never, never>, Record<never, never>>,
    'camera-create': RouteRecordInfo<'camera-create', '/camera/create', Record<never, never>, Record<never, never>>,
    'camera-edit-id': RouteRecordInfo<'camera-edit-id', '/camera/edit/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'camera-view-id': RouteRecordInfo<'camera-view-id', '/camera/view/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'config': RouteRecordInfo<'config', '/config', Record<never, never>, Record<never, never>>,
    'dashboard': RouteRecordInfo<'dashboard', '/dashboard', Record<never, never>, Record<never, never>>,
    'help': RouteRecordInfo<'help', '/help', Record<never, never>, Record<never, never>>,
    'jarvist': RouteRecordInfo<'jarvist', '/jarvist', Record<never, never>, Record<never, never>>,
    'jarvist-jarvist': RouteRecordInfo<'jarvist-jarvist', '/jarvist/jarvist', Record<never, never>, Record<never, never>>,
    'jarvist-view-people-counting': RouteRecordInfo<'jarvist-view-people-counting', '/jarvist/view/people-counting', Record<never, never>, Record<never, never>>,
    'settings': RouteRecordInfo<'settings', '/settings', Record<never, never>, Record<never, never>>,
    'settings-bak-edit': RouteRecordInfo<'settings-bak-edit', '/settings/bak/edit', Record<never, never>, Record<never, never>>,
    'settings-bak-old': RouteRecordInfo<'settings-bak-old', '/settings/bak/old', Record<never, never>, Record<never, never>>,
    'settings-bak-scheduler': RouteRecordInfo<'settings-bak-scheduler', '/settings/bak/scheduler', Record<never, never>, Record<never, never>>,
    'settings-bak-setting-modern': RouteRecordInfo<'settings-bak-setting-modern', '/settings/bak/setting-modern', Record<never, never>, Record<never, never>>,
  }
}
