// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class RTSPConfig {
    "schema": string;
    "host": string;
    "port"?: number;
    "path"?: string;
    "username"?: string;
    "password"?: string;

    /** Creates a new RTSPConfig instance. */
    constructor($$source: Partial<RTSPConfig> = {}) {
        if (!("schema" in $$source)) {
            this["schema"] = "";
        }
        if (!("host" in $$source)) {
            this["host"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RTSPConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): RTSPConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RTSPConfig($$parsedSource as Partial<RTSPConfig>);
    }
}
