// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class MJPEGStreamConfig {
    "inputFile": string;
    "frameRate": number;
    "port": number;
    "quality": number;

    /** Creates a new MJPEGStreamConfig instance. */
    constructor($$source: Partial<MJPEGStreamConfig> = {}) {
        if (!("inputFile" in $$source)) {
            this["inputFile"] = "";
        }
        if (!("frameRate" in $$source)) {
            this["frameRate"] = 0;
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("quality" in $$source)) {
            this["quality"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MJPEGStreamConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): MJPEGStreamConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MJPEGStreamConfig($$parsedSource as Partial<MJPEGStreamConfig>);
    }
}
