// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as buildinfo$0 from "../../../common/buildinfo/models.js";

export class Config {
    /**
     * App info
     */
    "appName": string;
    "appVersion": string;
    "environment": string;

    /**
     * Features
     */
    "isDev": boolean;
    "debugMode": boolean;
    "enableAnalytics": boolean;
    "buildInfo": buildinfo$0.BuildInfo;

    /** Creates a new Config instance. */
    constructor($$source: Partial<Config> = {}) {
        if (!("appName" in $$source)) {
            this["appName"] = "";
        }
        if (!("appVersion" in $$source)) {
            this["appVersion"] = "";
        }
        if (!("environment" in $$source)) {
            this["environment"] = "";
        }
        if (!("isDev" in $$source)) {
            this["isDev"] = false;
        }
        if (!("debugMode" in $$source)) {
            this["debugMode"] = false;
        }
        if (!("enableAnalytics" in $$source)) {
            this["enableAnalytics"] = false;
        }
        if (!("buildInfo" in $$source)) {
            this["buildInfo"] = (new buildinfo$0.BuildInfo());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Config instance from a string or object.
     */
    static createFrom($$source: any = {}): Config {
        const $$createField6_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("buildInfo" in $$parsedSource) {
            $$parsedSource["buildInfo"] = $$createField6_0($$parsedSource["buildInfo"]);
        }
        return new Config($$parsedSource as Partial<Config>);
    }
}

// Private type creation functions
const $$createType0 = buildinfo$0.BuildInfo.createFrom;
