// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class SiteCategory {
    "id": number;
    "name": string;

    /** Creates a new SiteCategory instance. */
    constructor($$source: Partial<SiteCategory> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SiteCategory instance from a string or object.
     */
    static createFrom($$source: any = {}): SiteCategory {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SiteCategory($$parsedSource as Partial<SiteCategory>);
    }
}
