// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetSiteCetegories(): $CancellablePromise<$models.SiteCategory[]> {
    return $Call.ByID(3456674585).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ValidateSiteCode(placeCode: string): $CancellablePromise<any> {
    return $Call.ByID(1478714102, placeCode);
}

// Private type creation functions
const $$createType0 = $models.SiteCategory.createFrom;
const $$createType1 = $Create.Array($$createType0);
