// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * StatsService untuk mengirim statistik
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../../github.com/wailsapp/wails/v3/pkg/application/models.js";

/**
 * Initialize menginisialisasi service dengan app instance dan konfigurasi
 */
export function InitService(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(4126218345, app);
}

/**
 * ServiceShutdown dijalankan saat aplikasi ditutup
 */
export function OnShutdown(): $CancellablePromise<void> {
    return $Call.ByID(3348999295);
}

/**
 * OnStartup dijalankan saat aplikasi dimulai
 */
export function OnStartup(options: application$0.ServiceOptions): $CancellablePromise<void> {
    return $Call.ByID(1841145726, options);
}

/**
 * StartSession memulai sesi baru dan mengembalikan ID sesi
 */
export function StartSession(): $CancellablePromise<number> {
    return $Call.ByID(444985464);
}
