// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../../github.com/wailsapp/wails/v3/pkg/application/models.js";

export function CloseApp(): $CancellablePromise<void> {
    return $Call.ByID(351029323);
}

export function InitService(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(3634661669, app);
}

export function OnShutdown(options: application$0.ServiceOptions): $CancellablePromise<void> {
    return $Call.ByID(1214027883, options);
}

export function OnStartup(options: application$0.ServiceOptions): $CancellablePromise<void> {
    return $Call.ByID(3340117066, options);
}

export function Restart(): $CancellablePromise<void> {
    return $Call.ByID(1949927207);
}
