// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BuildInfoService provides version information by directly reading info.json
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetCompanyName returns the company name from info.json
 */
export function GetCompanyName(): $CancellablePromise<string> {
    return $Call.ByID(2457046714);
}

/**
 * GetCopyright returns the copyright from info.json
 */
export function GetCopyright(): $CancellablePromise<string> {
    return $Call.ByID(2739669379);
}

/**
 * GetFileVersion returns the file version from info.json
 */
export function GetFileVersion(): $CancellablePromise<string> {
    return $Call.ByID(959425232);
}

/**
 * GetFullInfoJSON returns the entire info.json content as a JSON string
 */
export function GetFullInfoJSON(): $CancellablePromise<string> {
    return $Call.ByID(2517059221);
}

/**
 * GetProductName returns the product name from info.json
 */
export function GetProductName(): $CancellablePromise<string> {
    return $Call.ByID(957128754);
}

/**
 * GetProductVersion returns the product version from info.json
 */
export function GetProductVersion(): $CancellablePromise<string> {
    return $Call.ByID(3847536803);
}

export function LoadBuildInfo(): $CancellablePromise<$models.BuildInfo> {
    return $Call.ByID(4101004934).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * Reload allows manual reloading of the info.json file
 */
export function Reload(): $CancellablePromise<void> {
    return $Call.ByID(3355102083);
}

// Private type creation functions
const $$createType0 = $models.BuildInfo.createFrom;
