// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class BuildInfo {
    "file_version": string;
    "product_version": string;
    "company_name": string;
    "file_description": string;
    "legal_copyright": string;
    "product_name": string;
    "comments": string;

    /** Creates a new BuildInfo instance. */
    constructor($$source: Partial<BuildInfo> = {}) {
        if (!("file_version" in $$source)) {
            this["file_version"] = "";
        }
        if (!("product_version" in $$source)) {
            this["product_version"] = "";
        }
        if (!("company_name" in $$source)) {
            this["company_name"] = "";
        }
        if (!("file_description" in $$source)) {
            this["file_description"] = "";
        }
        if (!("legal_copyright" in $$source)) {
            this["legal_copyright"] = "";
        }
        if (!("product_name" in $$source)) {
            this["product_name"] = "";
        }
        if (!("comments" in $$source)) {
            this["comments"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BuildInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): BuildInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BuildInfo($$parsedSource as Partial<BuildInfo>);
    }
}
