// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../../github.com/wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CancelUpdate(): $CancellablePromise<void> {
    return $Call.ByID(786421021);
}

export function CheckForUpdates(): $CancellablePromise<$models.UpdateInfo | null> {
    return $Call.ByID(1173465837).then(($result: any) => {
        return $$createType1($result);
    });
}

export function CheckPendingUpdates(): $CancellablePromise<boolean> {
    return $Call.ByID(1086918273);
}

export function CleanupDownloads(): $CancellablePromise<void> {
    return $Call.ByID(3261110839);
}

export function DownloadUpdate(updateInfo: $models.UpdateInfo | null): $CancellablePromise<void> {
    return $Call.ByID(2027261943, updateInfo);
}

export function GetCurrentVersion(): $CancellablePromise<string> {
    return $Call.ByID(1887709277);
}

export function InitService(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(421849359, app);
}

export function InstallPendingUpdates(): $CancellablePromise<void> {
    return $Call.ByID(1485335090);
}

export function InstallUpdate(downloadPath: string): $CancellablePromise<void> {
    return $Call.ByID(3738629932, downloadPath);
}

export function InstallUpdateOnRestart(downloadPath: string): $CancellablePromise<void> {
    return $Call.ByID(140429532, downloadPath);
}

export function SetCurrentVersion(version: string): $CancellablePromise<void> {
    return $Call.ByID(1631117657, version);
}

export function SetUpdateServerURL(url: string): $CancellablePromise<void> {
    return $Call.ByID(3063537141, url);
}

// Private type creation functions
const $$createType0 = $models.UpdateInfo.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
