// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

export class CameraConnectionStatus {
    "camera_id": number;
    "camera_uuid": string;
    "is_connected": boolean;
    "last_checked": time$0.Time;
    "status_message"?: string;
    "error"?: string;

    /** Creates a new CameraConnectionStatus instance. */
    constructor($$source: Partial<CameraConnectionStatus> = {}) {
        if (!("camera_id" in $$source)) {
            this["camera_id"] = 0;
        }
        if (!("camera_uuid" in $$source)) {
            this["camera_uuid"] = "";
        }
        if (!("is_connected" in $$source)) {
            this["is_connected"] = false;
        }
        if (!("last_checked" in $$source)) {
            this["last_checked"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CameraConnectionStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): CameraConnectionStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CameraConnectionStatus($$parsedSource as Partial<CameraConnectionStatus>);
    }
}
