// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../../github.com/wailsapp/wails/v3/pkg/application/models.js";

export function CheckRunningProcesses(): $CancellablePromise<void> {
    return $Call.ByID(1952685884);
}

/**
 * ForceRemoveOrphanedStatusFiles menghapus file status yang tidak konsisten
 */
export function ForceRemoveOrphanedStatusFiles(): $CancellablePromise<void> {
    return $Call.ByID(214402817);
}

export function GetDetailedProcessStatus(processId: string): $CancellablePromise<string> {
    return $Call.ByID(4052588055, processId);
}

export function GetStatusClass(processId: string): $CancellablePromise<string> {
    return $Call.ByID(796519466, processId);
}

export function InitService(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(2756540053, app);
}

export function IsProcessRunning(processId: string): $CancellablePromise<boolean> {
    return $Call.ByID(2296274736, processId);
}

export function OnShutdown(): $CancellablePromise<void> {
    return $Call.ByID(1001473659);
}

export function OnStartup(options: application$0.ServiceOptions): $CancellablePromise<void> {
    return $Call.ByID(953414586, options);
}

export function RestartProcess(processId: string): $CancellablePromise<boolean> {
    return $Call.ByID(3046066980, processId);
}

export function RunBatFile(batFilename: string): $CancellablePromise<void> {
    return $Call.ByID(2984391706, batFilename);
}

export function StartStatusMonitor(): $CancellablePromise<void> {
    return $Call.ByID(1278536004);
}

export function StopProcess(processId: string): $CancellablePromise<boolean> {
    return $Call.ByID(2394937337, processId);
}

export function StopStatusMonitor(): $CancellablePromise<void> {
    return $Call.ByID(2517438352);
}

export function UpdateProcessStatusOnMissing(processId: string): $CancellablePromise<boolean> {
    return $Call.ByID(3214873463, processId);
}

export function VerifyAllProcessStatusConsistency(): $CancellablePromise<void> {
    return $Call.ByID(2474031769);
}

export function VerifyProcessStatusConsistency(processId: string): $CancellablePromise<void> {
    return $Call.ByID(737401748, processId);
}
